### ISSUE TITLE
[Feature] Support  Java 21

### ISSUE THREAD

**Issue by santitigaga** [bancolombia/scaffold-clean-architecture#397]
A few days ago Java 21 has long time support ([more information here](https://openjdk.org/projects/jdk/21/)). Will be great to support this version.

**Comment by luisgomez29** [comment]
Yes, for the clean architecture plugin it is recommended to remove support for Java versions 8 and 11, because Spring Boot versions 3.1.x and higher are used which support Java version 17 (minimum) and 21, and receive free security updates and bugfixes with support from community. The [Spring Initializr](https://start.spring.io/) page can be used as a reference.

For Java 21 [Spring Boot 3.2.0](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2-Release-Notes#support-for-virtual-threads) includes support for virtual threads and is compatible with [reactor-core 3.6.0](https://spring.io/blog/2023/10/31/what-new-is-coming-in-reactor-core-3-6-0#virtual-threads-support) which also introduces support for virtual threads.
