### ISSUE TITLE
Error when execute any tasks in Gradle  6.3

### ISSUE THREAD

**Issue by dbuos** [bancolombia/scaffold-clean-architecture#53]
When I execute gradle generateModel --name=[name] in gradle version > 6 (6.3), the plgin fails with following error: 

* Where:
Build file '/Users/daniel/Projects/banco/dojo-reactive/build.gradle' line: 23

* What went wrong:
An exception occurred applying plugin request [id: 'net.saliman.cobertura', version: '3.0.0']
> Failed to apply plugin [id 'net.saliman.cobertura']
   > Could not create task ':generateCoberturaReport'.
      > Could not create task of type 'GenerateReportTask'.
         > No signature of method: static org.gradle.util.DeprecationLogger.whileDisabled() is applicable for argument types: (net.saliman.gradle.plugin.cobertura.GenerateReportTask$1) values: [net.saliman.gradle.plugin.cobertura.GenerateReportTask$1@1a5e6363]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s                

FAILURE: Build failed with an exception.

**Comment by alx-val** [comment]
@dbuos I can work on this issue.

**Comment by dbuos** [comment]
Great! the issue is all yours! @alx-val

**Comment by santitigaga** [comment]
> 
> 
> @dbuos I can work on this issue.
Hi @alx-val , please check the PR in cobertura plugin https://github.com/stevesaliman/gradle-cobertura-plugin/pull/170 maybe this fix the error.

**Comment by alx-val** [comment]
The problem is when we use gradle local major to 6.1.1, because after this version, gradle  changes path and class DeprecationLogger  from import org.gradle.util.DeprecationLogger to import org.gradle.internal.deprecation.DeprecationLogger, so I recomend including in the instruction file Readme.md  but use gralde wrapper. When the PR ([link](https://github.com/stevesaliman/gradle-cobertura-plugin/pull/170/files)) for plugin net.saliman.gradle.plugin.cobertura is approved so we modify the wrapper version,  plugin architecture version and publish this. 

@santitigaga thanks for you help
